service: mms-scores-22-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    cors: true

functions:
  mmsScoresApi:
    name: ${sls:stage}-mmsScoresLambda
    handler: functions/apiScores.handler
    role: mmsScoresApiLambdaIam
    events:
      - http:
          path: api
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Api-Key
              - X-Last-Fetch-Key
            allowCredentials: false
resources:
  Resources:
    # TABLE SCORES
    mmsScoresApiDDBScores:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MMS_SCORES
        AttributeDefinitions:
          - AttributeName: scoreId
            AttributeType: S
          - AttributeName: gameId
            AttributeType: S
          - AttributeName: score
            AttributeType: N
        KeySchema:
          - AttributeName: scoreId
            KeyType: HASH
          - AttributeName: score
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gameIdIndex
            KeySchema:
              - AttributeName: gameId
                KeyType: HASH
              - AttributeName: score
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    # TABLE GAMES
    mmsScoresApiDDBGames:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MMS_GAMES
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
          - AttributeName: apiKey
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: apiKeyIndex
            KeySchema:
              - AttributeName: apiKey
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    # LAMBDA IAM ROLE
    mmsScoresApiLambdaIam:
      Type: AWS::IAM::Role
      Properties:
        RoleName: mmsScoresApiLambdaIamRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DynamoDBWriteAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:Query
                  Resource:
                    - !Sub '${mmsScoresApiDDBScores.Arn}'
                    - !Sub '${mmsScoresApiDDBScores.Arn}/index/*'
                    - !Sub '${mmsScoresApiDDBGames.Arn}'
                    - !Sub '${mmsScoresApiDDBGames.Arn}/index/*'

  Outputs:
    mmsScoresDynamoDbScoresARN:
      Description: 'MMS Scores DynamoDB Scores Table ARN'
      Value:
        'Fn::GetAtt': [mmsScoresApiDDBScores, Arn]
    mmsScoresDynamoDbGamesARN:
      Description: 'MMS Scores DynamoDB Scores Table ARN'
      Value:
        'Fn::GetAtt': [mmsScoresApiDDBGames, Arn]

plugins:
  - serverless-offline
